<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE RemoteDefinition [
   <!ELEMENT RemoteDefinition ( ip,username,foldername,isSelected,hostname ) >
   <!ELEMENT ip         (#PCDATA)>
   <!ELEMENT username   (#PCDATA)>
   <!ELEMENT foldername (#PCDATA)>
   <!ELEMENT isSelected (#PCDATA)>
   <!ELEMENT useSCP (#PCDATA)>
   <!ELEMENT useLOCALDEF (#PCDATA)>
   <!ELEMENT LOCALDEF (#PCDATA)>
   <!ELEMENT SHELLCMD (#PCDATA)>
]>
<RemoteDefinition>
   <ip> mars.hrsk.tu-dresden.de </ip>
   <username> schloeme </username>
   <foldername> benchit-remote </foldername>
   <isSelected> true </isSelected>
   <hostname> mars-ifort </hostname>
   <useSCP> false </useSCP>
   <useLOCALDEF> true </useLOCALDEF>
   <LOCALDEF> mars-ifort </LOCALDEF>
   <SHELLCMD> bash --login </SHELLCMD>
</RemoteDefinition>
<RemoteDefinition>
   <ip> mars.hrsk.tu-dresden.de </ip>
   <username> schloeme </username>
   <foldername> benchit </foldername>
   <isSelected> false </isSelected>
   <hostname> null </hostname>
   <useSCP> false </useSCP>
   <useLOCALDEF> false </useLOCALDEF>
   <LOCALDEF>  </LOCALDEF>
   <SHELLCMD> bash --login </SHELLCMD>
</RemoteDefinition>
